import { NextResponse } from 'next/server';

export async function POST(req) {
  try {
    const body = await req.json();
    const content = body;

    const title = content.title || 'Automated Test Suite';
    const cleanTitle = title.replace(/[^a-zA-Z0-9 ]/g, '');
    const testSteps = content.codeDetails?.testSteps || [
      { action: 'Execute API request', expected: 'Status 200 OK' }
    ];
    const apiUrl = content.codeDetails?.apiUrl || 'https://api.example.com/endpoint';
    const apiMethod = (content.codeDetails?.apiMethod || 'GET').toUpperCase();
    const apiHeaders = content.codeDetails?.apiHeaders || '{\n  "Content-Type": "application/json"\n}';
    const apiBody = content.codeDetails?.apiBody || '{}';

    // 1. Generate Playwright TypeScript Spec
    const playwrightTypeScript = `import { test, expect, request } from '@playwright/test';

/**
 * Test Suite: ${title}
 * Category: ${content.category || 'API Automation'}
 * Generated by QARP Test Engine
 */
test.describe('${cleanTitle}', () => {
  let apiContext;

  test.beforeAll(async () => {
    apiContext = await request.newContext({
      baseURL: '${apiUrl.split('/').slice(0, 3).join('/')}',
      extraHTTPHeaders: ${apiHeaders},
    });
  });

  test.afterAll(async () => {
    await apiContext.dispose();
  });

  test('Verify ${cleanTitle} execution', async () => {
${testSteps.map((step, idx) => `    // Step ${idx + 1}: ${step.action}`).join('\n')}
    const response = await apiContext.${apiMethod.toLowerCase()}('${apiUrl.replace(/^[a-z]+:\/\/[^\/]+/, '') || '/'}', {
${apiMethod !== 'GET' ? `      data: ${apiBody},\n` : ''}    });

    // Validations
    expect(response.ok()).toBeTruthy();
    expect([200, 201, 204]).toContain(response.status());
    
    const responseBody = await response.json().catch(() => null);
    if (responseBody) {
      console.log('Response Payload:', responseBody);
    }
  });
});
`;

    // 2. Generate Playwright JavaScript Spec
    const playwrightJavaScript = `const { test, expect, request } = require('@playwright/test');

test.describe('${cleanTitle}', () => {
  test('Execute test case', async () => {
    const apiContext = await request.newContext();
    const response = await apiContext.${apiMethod.toLowerCase()}('${apiUrl}', {
      headers: ${apiHeaders},
${apiMethod !== 'GET' ? `      data: ${apiBody},\n` : ''}    });

    expect(response.status()).toBeLessThan(400);
    const body = await response.json();
    expect(body).toBeTruthy();
  });
});
`;

    // 3. Generate RestAssured Java Class
    const restAssuredJava = `package com.qarp.tests;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.Test;
import static io.restassured.RestAssured.given;

public class ${cleanTitle.replace(/\s+/g, '')}Test {

    @Test
    public void test${cleanTitle.replace(/\s+/g, '')}() {
        RestAssured.baseURI = "${apiUrl}";

        Response response = given()
            .header("Content-Type", "application/json")
${apiMethod !== 'GET' ? `            .body("${apiBody.replace(/"/g, '\\"')}")\n` : ''}            .when()
            .${apiMethod.toLowerCase()}()
            .then()
            .extract().response();

        Assert.assertTrue(response.getStatusCode() < 400, "API returned non-2xx status code");
        System.out.println("Status: " + response.getStatusCode());
        System.out.println("Response: " + response.getBody().asPrettyString());
    }
}
`;

    // 4. Generate cURL Command
    const curlCommand = `curl -X ${apiMethod} "${apiUrl}" \\
  -H "Content-Type: application/json" \\
${apiMethod !== 'GET' ? `  -d '${apiBody}'` : ''}`;

    return NextResponse.json({
      title,
      playwrightTypeScript,
      playwrightJavaScript,
      restAssuredJava,
      curlCommand,
    });
  } catch (error) {
    console.error('POST /api/generate-tests error:', error);
    return NextResponse.json({ error: 'Failed to generate test files' }, { status: 500 });
  }
}
